config/routes.rb
Rails.application.routes.draw do

  
  root 'tasks#index'
  resources :tasks, except: [:index, :new, :edit, :show]
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @new_task = Task.new
    @tasks = Task.all
    @complete = @tasks.where complete: true
    @incomplete = @tasks.where complete: false
  end

  def create
    @task = Task.create task_params
    flash[:notice] = "Your task &ldquo;#{@task.title}&rdquo; was created."
    redirect_to :root
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    flash[:notice] = "Your task &ldquo;#{@task.title}&rdquo; was updated."
    redirect_to :root
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    flash[:notice] = "Your task &ldquo;#{@task.title}&rdquo; was removed."
    redirect_to :root
  end
  
  private
  
  def task_params
    params.require(:task).permit(:title, :complete)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:700|Roboto:300,300italic' rel='stylesheet' type='text/css'>
</head>
<body>
  
  <%= yield %>

</body>
</html>

app/views/tasks/index.html.erb
<div class="wrapper">
  <header>
    <h1>Todo</h1>
    <p>A simple&mdash;but <em>awesome</em>&mdash;to do list.</p>
  </header>
  
  <main>
    <% flash.each do |key, value| %>
      <p class="flash"><%= value.html_safe %></p>
    <% end %>
    
    <h2>Tasks:</h2>
    <% if @tasks.size > 0 %>
    
      <div class="incomplete-tasks">
        <% if @incomplete.size == 0 %>
          <p>Congratulations, you've completed all your tasks!</p>
          <img src="https://m.popkey.co/7f8895/ovQ5J.gif" alt="High Five!">
        <% else %>
          <p>
            You have <span class="incomplete-count"><%= @incomplete.size %></span> incomplete <%= 'task'.pluralize @incomplete.size %>.
            <% if @incomplete.size == 1 %>Nearly there!<% end %>
          </p>
        <% end %>
      </div>
      
      <ol class="tasks-list">
        <% @tasks.each_with_index do |task, i| %>
          <li class="task<% if task.complete %> complete<% end %>">
            <%= form_for task do |f| %>
              <label for="task_complete_<%= i %>">
                <%= f.check_box :complete, { id: "task_complete_#{i}" } %>
                <%#= task.title %>
              </label>
              
              <%= f.text_field :title %>
              <%= f.submit %>
              
              <!-- <a href="#" data-edit-task>edit</a> -->
              <%= link_to task_path(task), method: :delete, data: {confirm: "Are you sure you want to delete task #{task.title}?"}, class: 'delete-task' do %>delete<% end %>
            <% end %>
          </li>
        <% end %>
        <li class="new-task">
          <%= form_for @new_task, url: {action: "create"} do |f| %>
            <%= f.text_field :title %>
            <%= f.submit "Create a new task" %>
          <% end %>
        </li>
      </ol>

    <% else %>
      <p>You have no tasks. Why not create one?</p>
      
      <ol class="tasks-list">
        <li class="new-task">
          <%= form_for @new_task, url: {action: "create"} do |f| %>
            <%= f.text_field :title %>
            <%= f.submit "Create your first task" %>
          <% end %>
        </li>
      </ol>
    <% end %>
  </main>
</div>